version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    image: decentraland/webapp:dev
    env_file: .env
    ports:
      - '3000:3000'
    command: npm run start
    volumes:
      - .:/app
  test:
    image: decentraland/webapp:dev
    command: npm run test
    volumes:
      - .:/app
